/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUploadRouteImport } from './routes/_layout/upload'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutResultsRouteImport } from './routes/_layout/results'
import { Route as LayoutJdsRouteImport } from './routes/_layout/jds'
import { Route as LayoutHrQuestionsRouteImport } from './routes/_layout/hr-questions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUploadRoute = LayoutUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResultsRoute = LayoutResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJdsRoute = LayoutJdsRouteImport.update({
  id: '/jds',
  path: '/jds',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHrQuestionsRoute = LayoutHrQuestionsRouteImport.update({
  id: '/hr-questions',
  path: '/hr-questions',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/hr-questions': typeof LayoutHrQuestionsRoute
  '/jds': typeof LayoutJdsRoute
  '/results': typeof LayoutResultsRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/hr-questions': typeof LayoutHrQuestionsRoute
  '/jds': typeof LayoutJdsRoute
  '/results': typeof LayoutResultsRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/hr-questions': typeof LayoutHrQuestionsRoute
  '/_layout/jds': typeof LayoutJdsRoute
  '/_layout/results': typeof LayoutResultsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/upload': typeof LayoutUploadRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/hr-questions'
    | '/jds'
    | '/results'
    | '/settings'
    | '/upload'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/hr-questions'
    | '/jds'
    | '/results'
    | '/settings'
    | '/upload'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/hr-questions'
    | '/_layout/jds'
    | '/_layout/results'
    | '/_layout/settings'
    | '/_layout/upload'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/upload': {
      id: '/_layout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof LayoutUploadRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/results': {
      id: '/_layout/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof LayoutResultsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jds': {
      id: '/_layout/jds'
      path: '/jds'
      fullPath: '/jds'
      preLoaderRoute: typeof LayoutJdsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hr-questions': {
      id: '/_layout/hr-questions'
      path: '/hr-questions'
      fullPath: '/hr-questions'
      preLoaderRoute: typeof LayoutHrQuestionsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutHrQuestionsRoute: typeof LayoutHrQuestionsRoute
  LayoutJdsRoute: typeof LayoutJdsRoute
  LayoutResultsRoute: typeof LayoutResultsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUploadRoute: typeof LayoutUploadRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHrQuestionsRoute: LayoutHrQuestionsRoute,
  LayoutJdsRoute: LayoutJdsRoute,
  LayoutResultsRoute: LayoutResultsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUploadRoute: LayoutUploadRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
